project            = "myproject"
environment        = "prod"
region             = "us-east-1"
unique_id          = "001"
instance_class     = "db.r5.large"
master_username    = "admin"
master_password    = "SuperSecretPassword123"
kms_key_id         = "arn:aws:kms:us-east-1:123456789012:key/example-key-id"
